version: '3.8'
services:
  recbyhistory:
    image: ghcr.io/hrb9/watchlist-plus/recbyhistory:latest
    container_name: recbyhistory
    ports:
      - "5335:5335"
    environment:
      GEMINI_API_KEY: "your_gemini_key_here"
      TMDB_API_KEY: "your_tmdb_key_here"
      OVERSEERR_API_TOKEN: "your_overseerr_token_here"
      OVERSEERR_URL: "http://your_overseerr_url:5055"

  plexauthgui:
    image: ghcr.io/hrb9/watchlist-plus/plexauthgui:latest
    container_name: plexauthgui
    ports:
      - "5332:5332"
    environment:
      RECBYHISTORY_URL: "http://recbyhistory:5335"
      GEMINI_API_KEY: "your_gemini_key_here"
      TMDB_API_KEY: "your_tmdb_key_here"

  get_imdb_id:
    image: ghcr.io/hrb9/watchlist-plus/getimdbid:latest
    container_name: get_imdb_id
    ports:
      - "5331:5331"
    environment:
      RECBYHISTORY_URL: "http://getimdbid:5331"
      GEMINI_API_KEY: "your_gemini_key_here"
      TMDB_API_KEY: "your_tmdb_key_here"

